/*
  data.js — The single source of truth for the 99 Names of Allah (Asma ul-Husna).

  To edit a name's meaning or add/fix a Quran reference, just change it here.
  Each entry:
    id        : 1–99 (order follows the canonical At-Tirmidhi list)
    arabic    : the name in Arabic
    translit  : romanised (Latin) spelling
    english   : meaning in English
    urdu      : meaning in Urdu
    quranRef  : (optional) "surah:ayah", shown only when present
    quranUrl  : (optional) link to quran.com for that verse, for verification

  Quran references are included only for well-attested verses, and link out to
  quran.com so anyone can verify the source. Names without a reference simply
  won't show a reference block — that's intentional.
*/

const NAMES = [
  { id: 1,  arabic: "ٱلرَّحْمَٰن",            translit: "Ar-Rahman",            english: "The Most Compassionate",        urdu: "نہایت مہربان",                 quranRef: "55:1",  quranUrl: "https://quran.com/55/1" },
  { id: 2,  arabic: "ٱلرَّحِيم",              translit: "Ar-Raheem",            english: "The Most Merciful",             urdu: "بہت رحم کرنے والا",            quranRef: "1:3",   quranUrl: "https://quran.com/1/3" },
  { id: 3,  arabic: "ٱلْمَلِك",               translit: "Al-Malik",             english: "The King, The Sovereign",       urdu: "بادشاہ",                       quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 4,  arabic: "ٱلْقُدُّوس",             translit: "Al-Quddus",            english: "The Most Holy",                 urdu: "نہایت پاک",                    quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 5,  arabic: "ٱلسَّلَام",              translit: "As-Salam",             english: "The Source of Peace",           urdu: "سلامتی دینے والا",             quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 6,  arabic: "ٱلْمُؤْمِن",             translit: "Al-Mu'min",            english: "The Granter of Security",       urdu: "امن دینے والا",                quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 7,  arabic: "ٱلْمُهَيْمِن",           translit: "Al-Muhaymin",          english: "The Guardian, The Protector",   urdu: "نگہبان",                       quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 8,  arabic: "ٱلْعَزِيز",              translit: "Al-Aziz",              english: "The Almighty",                  urdu: "زبردست، غالب",                 quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 9,  arabic: "ٱلْجَبَّار",             translit: "Al-Jabbar",            english: "The Compeller",                 urdu: "زبردست، جبر کرنے والا",        quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 10, arabic: "ٱلْمُتَكَبِّر",          translit: "Al-Mutakabbir",        english: "The Supreme in Greatness",      urdu: "بڑائی والا",                   quranRef: "59:23", quranUrl: "https://quran.com/59/23" },
  { id: 11, arabic: "ٱلْخَالِق",              translit: "Al-Khaliq",            english: "The Creator",                   urdu: "پیدا کرنے والا",               quranRef: "59:24", quranUrl: "https://quran.com/59/24" },
  { id: 12, arabic: "ٱلْبَارِئ",              translit: "Al-Bari'",             english: "The Evolver, The Maker",        urdu: "بنانے والا",                   quranRef: "59:24", quranUrl: "https://quran.com/59/24" },
  { id: 13, arabic: "ٱلْمُصَوِّر",            translit: "Al-Musawwir",          english: "The Fashioner of Forms",        urdu: "صورت بنانے والا",              quranRef: "59:24", quranUrl: "https://quran.com/59/24" },
  { id: 14, arabic: "ٱلْغَفَّار",             translit: "Al-Ghaffar",           english: "The Repeatedly Forgiving",      urdu: "بہت بخشنے والا",               quranRef: "20:82", quranUrl: "https://quran.com/20/82" },
  { id: 15, arabic: "ٱلْقَهَّار",             translit: "Al-Qahhar",            english: "The Subduer, The Dominant",     urdu: "غالب، قہر والا",               quranRef: "13:16", quranUrl: "https://quran.com/13/16" },
  { id: 16, arabic: "ٱلْوَهَّاب",             translit: "Al-Wahhab",            english: "The Bestower",                  urdu: "بہت عطا کرنے والا",            quranRef: "3:8",   quranUrl: "https://quran.com/3/8" },
  { id: 17, arabic: "ٱلرَّزَّاق",             translit: "Ar-Razzaq",            english: "The Provider",                  urdu: "بہت رزق دینے والا",            quranRef: "51:58", quranUrl: "https://quran.com/51/58" },
  { id: 18, arabic: "ٱلْفَتَّاح",             translit: "Al-Fattah",            english: "The Opener, The Judge",         urdu: "کھولنے والا، فیصلہ کرنے والا", quranRef: "34:26", quranUrl: "https://quran.com/34/26" },
  { id: 19, arabic: "ٱلْعَلِيم",              translit: "Al-Alim",              english: "The All-Knowing",               urdu: "سب کچھ جاننے والا",            quranRef: "2:32",  quranUrl: "https://quran.com/2/32" },
  { id: 20, arabic: "ٱلْقَابِض",              translit: "Al-Qabid",             english: "The Withholder",                urdu: "تنگی دینے والا، روکنے والا",   quranRef: "2:245", quranUrl: "https://quran.com/2/245" },
  { id: 21, arabic: "ٱلْبَاسِط",              translit: "Al-Basit",             english: "The Extender",                  urdu: "کشادگی دینے والا",             quranRef: "2:245", quranUrl: "https://quran.com/2/245" },
  { id: 22, arabic: "ٱلْخَافِض",              translit: "Al-Khafid",            english: "The Abaser",                    urdu: "پست کرنے والا" },
  { id: 23, arabic: "ٱلرَّافِع",              translit: "Ar-Rafi'",             english: "The Exalter",                   urdu: "بلند کرنے والا" },
  { id: 24, arabic: "ٱلْمُعِزّ",              translit: "Al-Mu'izz",            english: "The Honourer",                  urdu: "عزت دینے والا",                quranRef: "3:26",  quranUrl: "https://quran.com/3/26" },
  { id: 25, arabic: "ٱلْمُذِلّ",              translit: "Al-Mudhill",           english: "The Dishonourer",               urdu: "ذلت دینے والا",                quranRef: "3:26",  quranUrl: "https://quran.com/3/26" },
  { id: 26, arabic: "ٱلسَّمِيع",              translit: "As-Sami'",             english: "The All-Hearing",               urdu: "سب کچھ سننے والا",             quranRef: "2:127", quranUrl: "https://quran.com/2/127" },
  { id: 27, arabic: "ٱلْبَصِير",              translit: "Al-Basir",             english: "The All-Seeing",                urdu: "سب کچھ دیکھنے والا",           quranRef: "17:1",  quranUrl: "https://quran.com/17/1" },
  { id: 28, arabic: "ٱلْحَكَم",               translit: "Al-Hakam",             english: "The Judge",                     urdu: "فیصلہ کرنے والا",              quranRef: "22:69", quranUrl: "https://quran.com/22/69" },
  { id: 29, arabic: "ٱلْعَدْل",               translit: "Al-Adl",               english: "The Utterly Just",              urdu: "انصاف والا، عادل" },
  { id: 30, arabic: "ٱللَّطِيف",              translit: "Al-Latif",             english: "The Subtle, The Gentle",        urdu: "باریک بین، مہربان",            quranRef: "67:14", quranUrl: "https://quran.com/67/14" },
  { id: 31, arabic: "ٱلْخَبِير",              translit: "Al-Khabir",            english: "The All-Aware",                 urdu: "باخبر",                        quranRef: "67:14", quranUrl: "https://quran.com/67/14" },
  { id: 32, arabic: "ٱلْحَلِيم",              translit: "Al-Halim",             english: "The Forbearing",                urdu: "بردبار",                       quranRef: "2:235", quranUrl: "https://quran.com/2/235" },
  { id: 33, arabic: "ٱلْعَظِيم",              translit: "Al-Azim",              english: "The Magnificent",               urdu: "بہت عظمت والا",                quranRef: "2:255", quranUrl: "https://quran.com/2/255" },
  { id: 34, arabic: "ٱلْغَفُور",              translit: "Al-Ghafur",            english: "The Much-Forgiving",            urdu: "بخشنے والا",                   quranRef: "2:173", quranUrl: "https://quran.com/2/173" },
  { id: 35, arabic: "ٱلشَّكُور",              translit: "Ash-Shakur",           english: "The Most Appreciative",         urdu: "قدر دان",                      quranRef: "64:17", quranUrl: "https://quran.com/64/17" },
  { id: 36, arabic: "ٱلْعَلِيّ",              translit: "Al-Ali",               english: "The Most High",                 urdu: "سب سے بلند",                   quranRef: "2:255", quranUrl: "https://quran.com/2/255" },
  { id: 37, arabic: "ٱلْكَبِير",              translit: "Al-Kabir",             english: "The Most Great",                urdu: "سب سے بڑا",                    quranRef: "13:9",  quranUrl: "https://quran.com/13/9" },
  { id: 38, arabic: "ٱلْحَفِيظ",              translit: "Al-Hafiz",             english: "The Preserver",                 urdu: "حفاظت کرنے والا",              quranRef: "11:57", quranUrl: "https://quran.com/11/57" },
  { id: 39, arabic: "ٱلْمُقِيت",              translit: "Al-Muqit",             english: "The Sustainer, The Nourisher", urdu: "روزی اور طاقت دینے والا",      quranRef: "4:85",  quranUrl: "https://quran.com/4/85" },
  { id: 40, arabic: "ٱلْحَسِيب",              translit: "Al-Hasib",             english: "The Reckoner",                  urdu: "حساب لینے والا",               quranRef: "4:86",  quranUrl: "https://quran.com/4/86" },
  { id: 41, arabic: "ٱلْجَلِيل",              translit: "Al-Jalil",             english: "The Majestic",                  urdu: "بزرگی والا" },
  { id: 42, arabic: "ٱلْكَرِيم",              translit: "Al-Karim",             english: "The Most Generous",             urdu: "کرم والا، سخی",                quranRef: "27:40", quranUrl: "https://quran.com/27/40" },
  { id: 43, arabic: "ٱلرَّقِيب",              translit: "Ar-Raqib",             english: "The Watchful",                  urdu: "نگہبان، نگرانی کرنے والا",     quranRef: "4:1",   quranUrl: "https://quran.com/4/1" },
  { id: 44, arabic: "ٱلْمُجِيب",              translit: "Al-Mujib",             english: "The Responsive",                urdu: "دعا قبول کرنے والا",           quranRef: "11:61", quranUrl: "https://quran.com/11/61" },
  { id: 45, arabic: "ٱلْوَاسِع",              translit: "Al-Wasi'",             english: "The All-Encompassing",          urdu: "وسعت والا",                    quranRef: "2:115", quranUrl: "https://quran.com/2/115" },
  { id: 46, arabic: "ٱلْحَكِيم",              translit: "Al-Hakim",             english: "The All-Wise",                  urdu: "حکمت والا",                    quranRef: "2:32",  quranUrl: "https://quran.com/2/32" },
  { id: 47, arabic: "ٱلْوَدُود",              translit: "Al-Wadud",             english: "The Most Loving",               urdu: "محبت کرنے والا",               quranRef: "85:14", quranUrl: "https://quran.com/85/14" },
  { id: 48, arabic: "ٱلْمَجِيد",              translit: "Al-Majid",             english: "The Most Glorious",             urdu: "بزرگی اور شان والا",           quranRef: "11:73", quranUrl: "https://quran.com/11/73" },
  { id: 49, arabic: "ٱلْبَاعِث",              translit: "Al-Ba'ith",            english: "The Resurrector",               urdu: "دوبارہ زندہ کرنے والا",        quranRef: "22:7",  quranUrl: "https://quran.com/22/7" },
  { id: 50, arabic: "ٱلشَّهِيد",              translit: "Ash-Shahid",           english: "The Witness",                   urdu: "گواہ",                         quranRef: "4:166", quranUrl: "https://quran.com/4/166" },
  { id: 51, arabic: "ٱلْحَقّ",                translit: "Al-Haqq",              english: "The Absolute Truth",            urdu: "سچا، حق",                      quranRef: "22:6",  quranUrl: "https://quran.com/22/6" },
  { id: 52, arabic: "ٱلْوَكِيل",              translit: "Al-Wakil",             english: "The Trustee, The Disposer",     urdu: "کارساز",                       quranRef: "3:173", quranUrl: "https://quran.com/3/173" },
  { id: 53, arabic: "ٱلْقَوِيّ",              translit: "Al-Qawiyy",            english: "The Most Strong",               urdu: "بہت طاقتور",                   quranRef: "22:74", quranUrl: "https://quran.com/22/74" },
  { id: 54, arabic: "ٱلْمَتِين",              translit: "Al-Matin",             english: "The Firm, The Steadfast",       urdu: "مضبوط",                        quranRef: "51:58", quranUrl: "https://quran.com/51/58" },
  { id: 55, arabic: "ٱلْوَلِيّ",              translit: "Al-Wali",              english: "The Protecting Friend",         urdu: "دوست، مددگار",                 quranRef: "42:28", quranUrl: "https://quran.com/42/28" },
  { id: 56, arabic: "ٱلْحَمِيد",              translit: "Al-Hamid",             english: "The Praiseworthy",              urdu: "تعریف کے لائق",                quranRef: "31:26", quranUrl: "https://quran.com/31/26" },
  { id: 57, arabic: "ٱلْمُحْصِي",             translit: "Al-Muhsi",             english: "The Counter, The Recorder",     urdu: "شمار کرنے والا",               quranRef: "72:28", quranUrl: "https://quran.com/72/28" },
  { id: 58, arabic: "ٱلْمُبْدِئ",             translit: "Al-Mubdi'",            english: "The Originator",                urdu: "پہلی بار پیدا کرنے والا",      quranRef: "85:13", quranUrl: "https://quran.com/85/13" },
  { id: 59, arabic: "ٱلْمُعِيد",              translit: "Al-Mu'id",             english: "The Restorer",                  urdu: "دوبارہ پیدا کرنے والا",        quranRef: "85:13", quranUrl: "https://quran.com/85/13" },
  { id: 60, arabic: "ٱلْمُحْيِي",             translit: "Al-Muhyi",             english: "The Giver of Life",             urdu: "زندگی دینے والا",              quranRef: "30:50", quranUrl: "https://quran.com/30/50" },
  { id: 61, arabic: "ٱلْمُمِيت",              translit: "Al-Mumit",             english: "The Bringer of Death",          urdu: "موت دینے والا",                quranRef: "57:2",  quranUrl: "https://quran.com/57/2" },
  { id: 62, arabic: "ٱلْحَيّ",                translit: "Al-Hayy",              english: "The Ever-Living",               urdu: "ہمیشہ زندہ",                   quranRef: "2:255", quranUrl: "https://quran.com/2/255" },
  { id: 63, arabic: "ٱلْقَيُّوم",             translit: "Al-Qayyum",            english: "The Self-Subsisting",           urdu: "سب کو قائم رکھنے والا",        quranRef: "2:255", quranUrl: "https://quran.com/2/255" },
  { id: 64, arabic: "ٱلْوَاجِد",              translit: "Al-Wajid",             english: "The Perceiver, The Finder",     urdu: "پانے والا" },
  { id: 65, arabic: "ٱلْمَاجِد",              translit: "Al-Majid",             english: "The Noble, The Glorious",       urdu: "بزرگی والا" },
  { id: 66, arabic: "ٱلْوَاحِد",              translit: "Al-Wahid",             english: "The One",                       urdu: "اکیلا، ایک",                   quranRef: "13:16", quranUrl: "https://quran.com/13/16" },
  { id: 67, arabic: "ٱلْأَحَد",               translit: "Al-Ahad",              english: "The Unique, The Indivisible",   urdu: "یکتا",                         quranRef: "112:1", quranUrl: "https://quran.com/112/1" },
  { id: 68, arabic: "ٱلصَّمَد",               translit: "As-Samad",             english: "The Eternal, Self-Sufficient",  urdu: "بے نیاز",                      quranRef: "112:2", quranUrl: "https://quran.com/112/2" },
  { id: 69, arabic: "ٱلْقَادِر",              translit: "Al-Qadir",             english: "The All-Powerful",              urdu: "قدرت والا",                    quranRef: "6:65",  quranUrl: "https://quran.com/6/65" },
  { id: 70, arabic: "ٱلْمُقْتَدِر",           translit: "Al-Muqtadir",          english: "The Omnipotent",                urdu: "پوری قدرت والا",               quranRef: "54:42", quranUrl: "https://quran.com/54/42" },
  { id: 71, arabic: "ٱلْمُقَدِّم",            translit: "Al-Muqaddim",          english: "The Expediter",                 urdu: "آگے کرنے والا" },
  { id: 72, arabic: "ٱلْمُؤَخِّر",            translit: "Al-Mu'akhkhir",        english: "The Delayer",                   urdu: "پیچھے کرنے والا" },
  { id: 73, arabic: "ٱلْأَوَّل",              translit: "Al-Awwal",             english: "The First",                     urdu: "سب سے پہلے",                   quranRef: "57:3",  quranUrl: "https://quran.com/57/3" },
  { id: 74, arabic: "ٱلْآخِر",                translit: "Al-Akhir",             english: "The Last",                      urdu: "سب سے آخر",                    quranRef: "57:3",  quranUrl: "https://quran.com/57/3" },
  { id: 75, arabic: "ٱلظَّاهِر",              translit: "Az-Zahir",             english: "The Manifest",                  urdu: "ظاہر",                         quranRef: "57:3",  quranUrl: "https://quran.com/57/3" },
  { id: 76, arabic: "ٱلْبَاطِن",              translit: "Al-Batin",             english: "The Hidden",                    urdu: "پوشیدہ، باطن",                 quranRef: "57:3",  quranUrl: "https://quran.com/57/3" },
  { id: 77, arabic: "ٱلْوَالِي",              translit: "Al-Wali",              english: "The Governor, The Patron",      urdu: "مالک، حاکم",                   quranRef: "13:11", quranUrl: "https://quran.com/13/11" },
  { id: 78, arabic: "ٱلْمُتَعَالِي",          translit: "Al-Muta'ali",          english: "The Most Exalted",              urdu: "سب سے بلند و بالا",            quranRef: "13:9",  quranUrl: "https://quran.com/13/9" },
  { id: 79, arabic: "ٱلْبَرّ",                translit: "Al-Barr",              english: "The Source of Goodness",        urdu: "احسان کرنے والا، نیکوکار",     quranRef: "52:28", quranUrl: "https://quran.com/52/28" },
  { id: 80, arabic: "ٱلتَّوَّاب",             translit: "At-Tawwab",            english: "The Acceptor of Repentance",    urdu: "توبہ قبول کرنے والا",          quranRef: "2:37",  quranUrl: "https://quran.com/2/37" },
  { id: 81, arabic: "ٱلْمُنْتَقِم",           translit: "Al-Muntaqim",          english: "The Avenger",                   urdu: "بدلہ لینے والا",               quranRef: "32:22", quranUrl: "https://quran.com/32/22" },
  { id: 82, arabic: "ٱلْعَفُوّ",              translit: "Al-Afuww",             english: "The Pardoner",                  urdu: "معاف کرنے والا",               quranRef: "4:99",  quranUrl: "https://quran.com/4/99" },
  { id: 83, arabic: "ٱلرَّؤُوف",              translit: "Ar-Ra'uf",             english: "The Most Kind",                 urdu: "بہت شفقت کرنے والا",           quranRef: "2:143", quranUrl: "https://quran.com/2/143" },
  { id: 84, arabic: "مَالِكُ ٱلْمُلْك",       translit: "Malik-ul-Mulk",        english: "Master of the Kingdom",         urdu: "بادشاہی کا مالک",              quranRef: "3:26",  quranUrl: "https://quran.com/3/26" },
  { id: 85, arabic: "ذُو ٱلْجَلَالِ وَٱلْإِكْرَام", translit: "Dhul-Jalali wal-Ikram", english: "Lord of Majesty and Honour", urdu: "عظمت اور بزرگی والا",        quranRef: "55:78", quranUrl: "https://quran.com/55/78" },
  { id: 86, arabic: "ٱلْمُقْسِط",             translit: "Al-Muqsit",            english: "The Equitable",                 urdu: "انصاف کرنے والا",              quranRef: "3:18",  quranUrl: "https://quran.com/3/18" },
  { id: 87, arabic: "ٱلْجَامِع",              translit: "Al-Jami'",             english: "The Gatherer",                  urdu: "جمع کرنے والا",                quranRef: "3:9",   quranUrl: "https://quran.com/3/9" },
  { id: 88, arabic: "ٱلْغَنِيّ",              translit: "Al-Ghani",             english: "The Self-Sufficient",           urdu: "بے نیاز، غنی",                 quranRef: "27:40", quranUrl: "https://quran.com/27/40" },
  { id: 89, arabic: "ٱلْمُغْنِي",             translit: "Al-Mughni",            english: "The Enricher",                  urdu: "غنی کرنے والا",                quranRef: "9:28",  quranUrl: "https://quran.com/9/28" },
  { id: 90, arabic: "ٱلْمَانِع",              translit: "Al-Mani'",             english: "The Withholder, The Preventer", urdu: "روکنے والا" },
  { id: 91, arabic: "ٱلضَّارّ",               translit: "Ad-Darr",              english: "The Distresser",                urdu: "نقصان پہنچانے والا" },
  { id: 92, arabic: "ٱلنَّافِع",              translit: "An-Nafi'",             english: "The Benefactor",                urdu: "نفع دینے والا" },
  { id: 93, arabic: "ٱلنُّور",                translit: "An-Nur",               english: "The Light",                     urdu: "نور، روشنی",                   quranRef: "24:35", quranUrl: "https://quran.com/24/35" },
  { id: 94, arabic: "ٱلْهَادِي",              translit: "Al-Hadi",              english: "The Guide",                     urdu: "ہدایت دینے والا",              quranRef: "22:54", quranUrl: "https://quran.com/22/54" },
  { id: 95, arabic: "ٱلْبَدِيع",              translit: "Al-Badi'",             english: "The Incomparable Originator",   urdu: "بے مثال پیدا کرنے والا",       quranRef: "2:117", quranUrl: "https://quran.com/2/117" },
  { id: 96, arabic: "ٱلْبَاقِي",              translit: "Al-Baqi",              english: "The Everlasting",               urdu: "ہمیشہ باقی رہنے والا",         quranRef: "55:27", quranUrl: "https://quran.com/55/27" },
  { id: 97, arabic: "ٱلْوَارِث",              translit: "Al-Warith",            english: "The Inheritor",                 urdu: "وارث",                         quranRef: "15:23", quranUrl: "https://quran.com/15/23" },
  { id: 98, arabic: "ٱلرَّشِيد",              translit: "Ar-Rashid",            english: "The Guide to the Right Path",   urdu: "درست راہ دکھانے والا" },
  { id: 99, arabic: "ٱلصَّبُور",              translit: "As-Sabur",             english: "The Most Patient",              urdu: "بہت صبر کرنے والا" },
];
